services:
  kratos:
    image: oryd/kratos:v1.2.0
    ports:
      - '4433:4433'
      - '4434:4434' 
    restart: unless-stopped
    command: serve -c /etc/config/kratos/kratos.yml
    depends_on:
      - kratos-migrate
    environment:
      - DSN=postgres://username:password@postgres:5432/auth?sslmode=disable
    volumes:
      - type: bind
        source: ./config/kratos/email-password
        target: /etc/config/kratos
  
  kratos-migrate:
    image: oryd/kratos:v1.2.0
    environment:
      - DSN=postgres://username:password@postgres:5432/auth?sslmode=disable
    volumes:
      - type: bind
        source: ./config/kratos/email-password
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    depends_on:
      - postgres

  keto:
    image: oryd/keto:v0.14.0
    ports:
      - "4466:4466"
      - "4467:4467"
    command: serve -c /home/ory/keto.yml
    restart: on-failure
    depends_on:
      - keto-migrate
    environment:
      - DSN=postgres://username:password@postgres:5432/auth?sslmode=disable
    volumes:
      - type: bind
        source: ./config/keto
        target: /home/ory

  keto-migrate:
    image: oryd/keto:v0.14.0
    command: migrate up -y
    restart: on-failure
    environment:
      - DSN=postgres://username:password@postgres:5432/auth?sslmode=disable
    volumes:
      - type: bind
        source: ./config/keto
        target: /home/ory
    depends_on:
      - postgres

  oathkeeper:
    image: oryd/oathkeeper:v0.40.9
    ports:
      - "4455:4455"  
      - "4456:4456" 
    command: serve --config=/etc/config/oathkeeper/config.yaml
    volumes:
      - type: bind
        source: ./config/oathkeeper
        target: /etc/config/oathkeeper
    restart: on-failure

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
