version: v0.13.0

serve:
  public:
    base_url: http://kratos:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:3333/welcome
  allowed_return_urls:
    - http://127.0.0.1:3333

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:3333/error

    settings:
      ui_url: http://127.0.0.1:3333/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:3333/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:3333/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:3333/welcome

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:3333/login

    login:
      ui_url: http://127.0.0.1:3333/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:3333/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

feature_flags:
  use_continue_with_transitions: true

session:
  lifespan: 12h
  earliest_possible_extend: 12h

