serve:
  proxy:
    port: 4455 # run the proxy at port 4455
  api:
    port: 4456 # run the api at port 4456

access_rules:
  repositories:
    - file:///etc/config/oathkeeper/rules.json

mutators:
  noop:
    enabled: true
  header:
    enabled: true
    config:
      headers:
        X-User-ID: "{{ print .Subject }}"

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true
  remote_json:
    enabled: true
    config:
      remote: http://keto:4466/relation-tuples/check
      payload: |
        {
          "namespace": "hello",
          "object": "{{ trimPrefix .MatchContext.URL.Path "/hello" }}",
          "relation": "{{ print .MatchContext.Method }}",
          "subject_id": "{{ print .Subject }}"
        }

authenticators:
  noop:
    enabled: true
  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      extra_from: "@this"
      subject_from: "identity.id"
      only:
        - ory_kratos_session
